USE [master]
GO
/****** Object:  Database [TcmbExchangeRates]    Script Date: 22.02.2018 00:38:27 ******/
CREATE DATABASE [TcmbExchangeRates]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TcmbExchangeRates', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\TcmbExchangeRates.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TcmbExchangeRates_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\TcmbExchangeRates_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [TcmbExchangeRates] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TcmbExchangeRates].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TcmbExchangeRates] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET ARITHABORT OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TcmbExchangeRates] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TcmbExchangeRates] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TcmbExchangeRates] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TcmbExchangeRates] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TcmbExchangeRates] SET  MULTI_USER 
GO
ALTER DATABASE [TcmbExchangeRates] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TcmbExchangeRates] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TcmbExchangeRates] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TcmbExchangeRates] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [TcmbExchangeRates] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'TcmbExchangeRates', N'ON'
GO
ALTER DATABASE [TcmbExchangeRates] SET QUERY_STORE = OFF
GO
USE [TcmbExchangeRates]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [TcmbExchangeRates]
GO
/****** Object:  User [test]    Script Date: 22.02.2018 00:38:27 ******/
CREATE USER [test] FOR LOGIN [test] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [test]
GO
ALTER ROLE [db_accessadmin] ADD MEMBER [test]
GO
ALTER ROLE [db_securityadmin] ADD MEMBER [test]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [test]
GO
ALTER ROLE [db_backupoperator] ADD MEMBER [test]
GO
ALTER ROLE [db_datareader] ADD MEMBER [test]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [test]
GO
/****** Object:  Table [dbo].[tbl_CurrencyExchangeRate]    Script Date: 22.02.2018 00:38:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_CurrencyExchangeRate](
	[CurrencyExchangeRateID] [int] IDENTITY(1,1) NOT NULL,
	[CurrencyCode] [nvarchar](3) NOT NULL,
	[BanknoteBuying] [decimal](12, 5) NULL,
	[BanknoteSelling] [decimal](12, 5) NULL,
	[ForexBuying] [decimal](12, 5) NULL,
	[ForexSelling] [decimal](12, 5) NULL,
	[CrossRateUSD] [decimal](12, 5) NULL,
	[CrossRateOther] [decimal](12, 5) NULL,
	[Unit] [int] NULL,
	[CurrencyExchangeRateDate] [datetime] NOT NULL,
	[CurrencyExchangeRateShortDate] [bigint] NOT NULL,
 CONSTRAINT [PK_tbl_CurrencyExchangeRate] PRIMARY KEY CLUSTERED 
(
	[CurrencyExchangeRateID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [TcmbExchangeRates] SET  READ_WRITE 
GO
